server:
  port: 9010
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zhenxin
    password: 1234
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-wait: 10000

app:
  server: http://localhost:${server.port}

img:
  server: http://119.29.214.244:8090
#
#    13-7
#119.29.214.244
# 日志配置
# 区分 info 和 error 日志
# 每天产生一个日志文件
# 1
#logging:
#  pattern:
#    console: "%d -- %msg%n"
#  file: logs/sell.log
#  level: trace